CREATE TABLE IF NOT EXISTS "Domain" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
  domain TEXT NOT NULL UNIQUE,
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  "verificationToken" TEXT NOT NULL
);

ALTER TABLE "QR" ADD COLUMN IF NOT EXISTS domain_id UUID REFERENCES "Domain"(id);
