import type { Metadata } from "next";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import { Montserrat, Geist_Mono, Orbitron } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"
import { getCustomDomainFallbackUrlForHostname } from "@/lib/custom-domains";
import { getRequestHostname, isPrimaryAppHost } from "@/lib/qr-url";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["200", "400", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "the qr code co.",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/favicon.ico", sizes: "any" },
    ],
    shortcut: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const requestHeaders = await headers();
  const hostname = getRequestHostname({ headers: requestHeaders });

  if (hostname && !isPrimaryAppHost(hostname)) {
    redirect(await getCustomDomainFallbackUrlForHostname(hostname));
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.variable} ${geistMono.variable} ${orbitron.variable} bg-sidebar antialiased`}
      ><StackProvider app={stackServerApp}><StackTheme>
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
          {children}
          <Toaster richColors/>
          <SpeedInsights/>
          <Analytics/>
        </ThemeProvider>
      </StackTheme></StackProvider></body>
    </html>
  );
}
